### ISSUE TITLE
Some monitors/resolutions crop title screens weird

### ISSUE THREAD

**Issue by IronWillGames** [IronWillGames/AshenEmpires#1]
Screen res is 2560x1440

![image](https://user-images.githubusercontent.com/2902872/188313178-a78302ca-dc91-4586-9b77-40e088c9ff6a.png)

https://discord.com/channels/695812967463256084/706609766222528602/1015950490179207239

**Comment by marmotini** [comment]
I think it could be unrelated to the resolution of the monitor itself, but is related to the resolution of the game window. When I set my resolution in-game to be 1920x1080 and then go back to the character select screen, that graphic looks perfect. When I change it to anything else, even if it's the same ratio as the 1920x1080 (i.e. 1600x900) there are black bars.

**Comment by davidjreese** [comment]
Dupes:
- https://github.com/IronWillGames/AshenEmpires/issues/35

**Comment by davidjreese** [comment]
Might have found this. Need someone who can repo it to test in STAGE

**Comment by davidjreese** [comment]
Fixed! @moneybill was able to confirm it worked for him!

**Comment by curxxx** [comment]
Not fixed

**Comment by curxxx** [comment]
<img width="926" alt="Screen Shot 2022-09-08 at 10 26 53 PM" src="https://user-images.githubusercontent.com/5109969/189259566-ab97aa09-35f8-4eab-b3fc-5baedca99425.png">
