### ISSUE TITLE
Magic Skinning Knife has really high degrade rate

### ISSUE THREAD

**Issue by curxxx** [IronWillGames/AshenEmpires#103]
See the screenshot. Many users are complaining about the very high degradation rate of the Magic Skinning Knife - especially given their rarity on Ascension server.

![unknown-5](https://user-images.githubusercontent.com/5109969/194719328-b0a38801-e55b-44af-a5dc-2a0e3d9cace5.png)

**Comment by hgesler** [comment]
The degrade chance on this is tied to Skill level and total dex. I have a ticket open to review it. Duplicated
