### ISSUE TITLE
Unable to type value in merchant quantity window

### ISSUE THREAD

**Issue by reikoshea** [IronWillGames/AshenEmpires#11]
Sometimes the merchant quantity window loses focus, and entering numbers will cause hotbars to [de]activate. I think this is due to the hunters journal changes.

![image](https://user-images.githubusercontent.com/4267199/188335069-91803fba-6f54-465f-bab6-125b17b48012.png)

**Comment by davidjreese** [comment]
Still happens? Even after you click back in the box to set focus again?

**Comment by reikoshea** [comment]
It works if you click back in the text box with the number in it. Simply reporting because it's definitely different than the old functionality.

**Comment by davidjreese** [comment]
This works as designed now. Because we now allow focus to go away from input boxes (Monster Manual), this had to be allowed everywhere. Clicking on the box should give it focus again like you verified so thats working.
