### ISSUE TITLE
Disruption Spell

### ISSUE THREAD

**Issue by GM-Odran** [IronWillGames/AshenEmpires#119]
Player reported bug with spell Disruption.

A player with lvl 100 mind cannot cast disruption on another player that has 50+ Mind Resistance (which is as intended), however a player with Mind lvl 1-99 is able to cast the spell on a player with 50+ Mind Resistance.

TLDR, any player with 50+ Mind Resistance should be immune from having the Disruption spell cast on them, however at the moment that limitation is only being applied to casters with 100 mind, less than 100 can cast it regardless of the attacked players Mind Resistance.

**Comment by hgesler** [comment]
Will be fixed in tonight's patch
