### ISSUE TITLE
DETAILS button on Store menu in game sending to pixelminegames.com instead of ironwillgames.com

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/AshenEmpires#12]
In game menu sends to the old secure site. Should send to the new, eg

https://customer.ironwillgames.com/StoreProductDataSheet.aspx?id=76

**Comment by davidjreese** [comment]
Fixed - as well as some text about getting the launcher from somewhere other than steam.

**Comment by hgesler** [comment]
Verified
