### ISSUE TITLE
Obisidian Seeker Recipe

### ISSUE THREAD

**Issue by GM-Odran** [IronWillGames/AshenEmpires#127]
Obsidian Seeker recipe is currently wrong, it crafts them at a ratio of 1:1 now

**Comment by hgesler** [comment]
What do you mean - 1 potion makes 1 seeker? Should be 1 potion makes 20 seekers.

**Comment by GM-Odran** [comment]
@hgesler it looks to have been changed to 1:20, up until very recently it was using Obisidian at 1:1 (ie; 1000 Obisidian used to craft 1000 Obsidian Seekers)

![image](https://user-images.githubusercontent.com/112826917/199852569-983f9734-60e2-4c36-b9a0-031af48eb7a3.png)
