### ISSUE TITLE
The Bane of Whisperdale

### ISSUE THREAD

**Issue by Ashial** [IronWillGames/AshenEmpires#131]
after finishing the first part of killing gloom lights you get to the boots part by killing greater lights, the quest gives no update on finding or not finding the item which i assume means quest is bugged

**Comment by hgesler** [comment]
Added failure confirmation message. Quest updates properly.

**Comment by Ashial** [comment]
![AshenEmpires00001](https://user-images.githubusercontent.com/118044709/202835083-2864522f-3f04-4753-a292-4016de2eb9c1.jpeg)

**Comment by Ashial** [comment]
is the quest update going to be added in future update?

**Comment by Ashial** [comment]
![AshenEmpires00002](https://user-images.githubusercontent.com/118044709/202836037-3349b4f0-3218-45de-b1cb-a3eb57d77325.jpeg)

the first part of the quest gives you the "did not find" but 2nd part doesn't, it took me 54 of pretty low spawn mobs to get the quest item which was a few hours of being down there.  this is going to discourage many people from even finishing this quest, especially new players.

**Comment by hgesler** [comment]
It is going to be updated yes. The fix is in but not applied until tonight's patch. Thank you for your feedback.
