### ISSUE TITLE
Allow unlimited valinor orb resets

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/AshenEmpires#136]
Currently players only allowed 1 orb reset. Suggestion to remove this limitation.

**Comment by SonjiWf** [comment]
It would be a great idea imo. Allw a player to get to level 10 on valinor and try out different builds and weapon combos before they commit to it for the main land. a lvl 100 free reset would be nice as well but i wont push my luck lol.

**Comment by EJaynes** [comment]
Patched in test. Closing ticket. Will deploy with next live patch branch.
