### ISSUE TITLE
Snow Elves stuck in TR Lands

### ISSUE THREAD

**Issue by EJaynes** [IronWillGames/AshenEmpires#137]
Coords: 2410  710
![image](https://user-images.githubusercontent.com/108539164/205726176-9973bab4-76df-475d-bddc-d20b0dcc66f7.png)

**Comment by HitinRun** [comment]
![stuck](https://user-images.githubusercontent.com/119949710/205934795-c5105b80-5e83-47f3-ac1a-9ab5ccad34ff.PNG)

**Comment by HitinRun** [comment]
![trapped](https://user-images.githubusercontent.com/119949710/206868439-ff584b6a-0c22-424f-b0f5-862d16bb8731.PNG)
![trapped 2](https://user-images.githubusercontent.com/119949710/206868442-31a1eeb9-f54e-4290-8595-c841b5fac456.PNG)

**Comment by hgesler** [comment]
Please let this be fixed once and for all
