### ISSUE TITLE
Cannot cast mage spells on Deadwillows

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/AshenEmpires#15]
Cannot cast mage spells on the creature Deadwillow. Well this one has been around for a while and I feel like I created it somehow when we added identification skill but Bahamut says it is bc of the heal on them.

**Comment by EJaynes** [comment]
As a note other creatures like Orc Renegade Mages or Dragons heal themselves, but aren't prone to this problem.

**Comment by hgesler** [comment]
So area of effect can be cast on them. I checked walk types and other settings in npc editor and don't see what's so special about these hunky junk trunks. Can be attacked with melee/ranged attacks.

**Comment by hgesler** [comment]
Scripts on them for spawning fragments also looks good (compared with golems/ice golems)

**Comment by hgesler** [comment]
It is difficult but possible to target them with Lacerate. To do this, make sure to be using the new cursor option.

1. Spawn a deadwillow
2. Select Lacerate (mind spell) from hotbar. Notice that when hovering over Deadwillow with mage targeting cursor, the creature sprite jumps down slightly - similar behavior happens when you have selected them with a spell that can't be cast on them (like Runesight).
3. Move cursor away from creature, and deselect spell so that you have a normal cursor. Hover over creature until you see the double bounding box (using new cursor option, not original cursor; it shows two, not just one, boxes with the inner box moving). Quickly select the Lacerate spell while the bounding box has selected it and lo and behold, you can cast on it. I'd guess other spells act the same way. It's almost as if the shape/sprite/animation or something is wrong with the deadwillow - the game does not have a pixel to target. It is a more dated model than the treant/ghost willow which have more detail. I'd guess a new anim was made for this creature specificall because of this issue.

**Comment by hgesler** [comment]
Roots have same issue

**Comment by hgesler** [comment]
![image](https://user-images.githubusercontent.com/74884462/188709008-3c6f1d63-02c2-404a-a17f-0fdee1cf60b1.png)
notice no bounding box for spell lacerate

![image](https://user-images.githubusercontent.com/74884462/188709070-c1df849e-a2ed-4ffe-8f48-a93a46b42b59.png)
deselect spell then use cursor to bring up bouncing bounding box (new cursor option)

![image](https://user-images.githubusercontent.com/74884462/188709277-c4e30f54-8c41-4a02-8c0b-02cf34128e16.png)
while bounding box is selecting it use hotkey F# to select lacerate, and cast using left click

**Comment by hgesler** [comment]
Sigh. It is because it was flagged as a corpse in the editor. Probably when we were testing that new option.

**Comment by hgesler** [comment]
Roots had same issue
