### ISSUE TITLE
Berserker Potion tooltip says it lasts 10 seconds but it actually lasts 15 seconds

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/AshenEmpires#159]
![image](https://user-images.githubusercontent.com/72478718/222962327-69996662-c1d9-4789-b2a0-825826be2c45.png)

![image](https://user-images.githubusercontent.com/72478718/222962353-db9b7fcb-d90f-4899-9342-fd823874e365.png)

**Comment by hgesler** [comment]
Fixed for next patch
