### ISSUE TITLE
Legacy Cloak can't be repaired with repair potions

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/AshenEmpires#162]
Have a Legacy Cloak at 850/995 HP, tried using Potion of Repair on it and it says "That item does not need to be repaired."

Not a huge issue though since we can destroy it and claim another one from the Mage of Lotor in order to get it back to full AC effectiveness, just a bit annoying to do that each time after dying or just deal with the lower AC from having damaged gear

**Comment by hgesler** [comment]
As designed because players can salvage it if it is allowed to be repaired, creating infinite malacinth.
