### ISSUE TITLE
Meroven Guards Bugged will not Attack Temp Players attacking other players

### ISSUE THREAD

**Issue by TheDigitalDecay** [IronWillGames/AshenEmpires#168]
A temp player can attack and kill any other player in the town of meroven and the guards will not chase. if you stand next to the guard they attack but they will not follow. This allows grief play with the Spawn Increase Altar. Even if you successfully killed the temp player they will respawn and begin attacking again which is not fair for other players who are not wanted.

**Comment by curxxx** [comment]
as designed lol

**Comment by hgesler** [comment]
Guards in evil towns are there to kill hostile enemies coming in, not police
