### ISSUE TITLE
Sinister Cauldron needs hooked up to alchemy scripts

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/AshenEmpires#170]
It is placeable but not usable atm.

**Comment by SonjiWf** [comment]
i think this would be a good cauldron to make it give random quanities of potions back. like it will average maybe 15 pots per instead of 10 (at 100 alch) but you could get 1 potion or maybe 100 potions from it from a single attempt too lol

**Comment by hgesler** [comment]
Fixed and now working with patch as a just different colored cauldron; no special on it atm.
