### ISSUE TITLE
Enhancement - Display debuffs with timers on monster plaque

### ISSUE THREAD

**Issue by Aegon121** [IronWillGames/AshenEmpires#174]
Can all debuffs along with timers be displayed on monster info plaque when right clicking it? See screenshot (don't mind the terrible editing)

![9_4_2023 6_22_51 PM](https://github.com/IronWillGames/AshenEmpires/assets/144071806/e4b35754-2b2b-4017-9703-bb7410fcfeb9)

**Comment by hgesler** [comment]
Duplicate
