### ISSUE TITLE
Mage spell spelled incorrectly

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/AshenEmpires#178]
Repentenance... Repentance?
![image](https://github.com/IronWillGames/AshenEmpires/assets/30209039/776ed17f-49bc-4444-a1f0-40f7cade269d)

**Comment by hgesler** [comment]
It is technically mispelled but its mispelled in such a way it feels purposeful to me? Because repentance is the act of turning away from sin, not some damaging spell?

**Comment by hgesler** [comment]
I debated about changing this multiple times but think I'm going to leave it as is for now
