### ISSUE TITLE
Player Pets Remain After Teleporting Away on Guard/Stay.

### ISSUE THREAD

**Issue by EJaynes** [IronWillGames/AshenEmpires#19]
Player pets need to be bound to player's play area plus a small buffer.

Currently you can leave your pets somewhere by telling them to Stay/Guard Location then teleporting away. This causes players to use pets to lay in wait for bosses (if pet dies, they know boss spawned), other players, or an assortment of other options to abuse. The player's followers just need to be hard enforced to a specified distance from player or it snaps them to player (similar to the catch-up speed factor that's applied while using the Follow command for slower moving NPCs).

**Comment by davidjreese** [comment]
Foxed - now, Abandon pets will eventually die... so sad.

**Comment by hgesler** [comment]
verified
