### ISSUE TITLE
Druid Staff Summoned Wyverns Summons Rogue Wyvern

### ISSUE THREAD

**Issue by EJaynes** [IronWillGames/AshenEmpires#20]
On some occasions while using the Druid's Staff on hit it will summon a hostile wyvern (' Summoned Wyvern ') instead of failing to summon due to too many followers already existing. This Summoned Wyvern is hostile to the player, and attacks them.

Reproduction by equipping Druid's Staff and hitting target to spawn two Wyvern followers. Dismiss one follower. Attack again to spawn two more followers. Dismiss one of the new additional followers. Attack again to spawn another two wyverns and one will be a rogue Summoned Wyvern that is hostile. This also happens to players when double-attack occurs (which is what happens most often natively), but the above method is easier to reproduce.

**Comment by hgesler** [comment]
Resolved this in script. Will cap max wyvern followers at 2 and will summon 1 at a time (was summoning 2 at a time, and looking for greater than 2 followers)

**Comment by hgesler** [comment]
Was not working how I wanted to so I had to rework this script and other summoned creature scripts; had to set data to something other than 1 or 0, using multiple values, creatures should remove their added value once dead/destroyed/dismissed. Fixed for next build.
