### ISSUE TITLE
Alignment gain on killing evil players.

### ISSUE THREAD

**Issue by EJaynes** [IronWillGames/AshenEmpires#21]
New problem, higher rep (good) killing lower rep (evil) is actually giving them reputation gain, rather than no loss.

**Comment by curxxx** [comment]
Is this a problem? Seems to make sense logically.

**Comment by EJaynes** [comment]
Should just yield nothing. No loss.

**Comment by curxxx** [comment]
Logically I disagree. Players should be rewarded rep for killing evil players.

**Comment by hgesler** [comment]
Could be abused however if you keep an evil alt around to rekill and jump reputation easily. 

Fix for this in and will be tested/implemented in next build (9.6)
