### ISSUE TITLE
Party Menu Healing Issues in Lotor + Taly Dungeons

### ISSUE THREAD

**Issue by TheDigitalDecay83** [IronWillGames/AshenEmpires#210]
As of late seems since last server crash or right before we are having problems healing through the party menu in the taly + lotor dungeons. Last night i tried to heal a player and could not no messages or anything, i manually targeted him healed him and then tried again in the party list and it worked.

**Comment by hgesler** [comment]
I'm guessing this is similar to the issue with server restarting and you happen to be the first party formed at a new server (party ID is 0 then).

**Comment by hgesler** [comment]
See bug #151

**Comment by TheDigitalDecay83** [comment]
> I'm guessing this is similar to the issue with server restarting and you happen to be the first party formed at a new server (party ID is 0 then).

similar yes, however its been doing it on a regular basis since the last server reset as long as we manually heal first then the party window works. that was the first thing we thought of was the first party id being 0 but its been consistent since the server reset.
