### ISSUE TITLE
Suggestion - Remove "solo" tag from monsters

### ISSUE THREAD

**Issue by Midnizzle** [IronWillGames/AshenEmpires#213]
At this stage of the game, I don't believe it's necessary to have monstered labeled solo. A majority of the low level ones especially, are considered solo and do not give bonus exp. This can deter newer players from continuing as it slows progress. 

Example: Spider, Fire Ant, Small Grizzly Bear, Triddle, Snake, Bat, Firefly Swarm, Rotten Zombie, Skeleton, Wolf

**Comment by hgesler** [comment]
![image](https://github.com/user-attachments/assets/dc6882bb-6572-446b-8eed-265a769c69d8)
