### ISSUE TITLE
Items into Cabinets

### ISSUE THREAD

**Issue by ArunFitz** [IronWillGames/AshenEmpires#233]
Some items can not be placed into specific cabinets:
-blood lich torc into armor cabinet
-blood lich robe into armor cabinet
-blood lich trousers into armor cabinet
-spell slinger into missile weapons cabinet

**Comment by hgesler** [comment]
Fixed for next build, but spell slinger will need checked as it is a weird spell/archery hybrid and I'm not sure if fixing it for this breaks it in other ways.
