### ISSUE TITLE
Music in new areas

### ISSUE THREAD

**Issue by ArunFitz** [IronWillGames/AshenEmpires#234]
new left side area and right side area of blue dragons does not have music
new left side area of gold dragons does not play music
new north side area of red dragons does not play music
new left side area of greater dragon cave does not play music
the music stops playing as soon as you enter these areas, green level and nith level are fine

**Comment by hgesler** [comment]
Fixed, though this has given me anxiety to discover so many other missing music areas in the dungeon level 🤦
