### ISSUE TITLE
Graal Roachard Spawn Timer Bug or As Intended ?

### ISSUE THREAD

**Issue by TheDigitalDecay83** [IronWillGames/AshenEmpires#238]
Word has it that Graal has a predictable timer and spawns every 5 days allowing some to keep the boss on lock down from other players.
Wanted to bring it to the attention of devs for potential review and or randomization of the original 4-7 day timer or confirmation of as intended.
Suggestion: Would also be acceptable to change the boss removing the timer and setting as resource spawn only (Upping Required Resources) similar to dunk boss.

**Comment by hgesler** [comment]
It is currently randomized after the boss is killed. There is no way of knowing what the new time will be and can be 4-7 days from its death.
