### ISSUE TITLE
Magic crafting tools not  giving bonus exp

### ISSUE THREAD

**Issue by Sreading88** [IronWillGames/AshenEmpires#26]

**Comment by hgesler** [comment]
From Discord:

Farming Almanac -> Working (Increases XP - tested on A) 
Felling Axe -> Working (Increases XP - tested on A) 
Stonebiter Pickaxe - Working (Increases XP)
Silver Spoon -> Working (Increases XP - tested on L) 
Heavy Foraging Stick -> Working (Increases XP - tested on L)
Foraging Smock -> Working (Increases XP - must be worn - correctly stacks with Heavy Foraging Stick - tested on L)
Mystic Scissors -> Working (Increases XP - tested on L)
Two Bladed Saw -> Working (Increases XP - tested on L)
Logging Axe -> Working (Increases XP - works better than Felling Axe, which is correct - tested on L)

Carpentry Toolset -> NOT Working (it is the second item I've tested which gives a message that it helps you, and so far neither of them are working - maybe that's related? - tested on L)
Anvil of Veldan -> NOT Working (gave a message in chat that "The Anvil of Veldan increases your skill," but it did not result in any change in XP - tested on L)

**Comment by hgesler** [comment]
Found the issue with carpentry; was tied to carpentry repair skill instead of carpentry.

Need to work on this some more; attempted a fix and it appears to be giving double xp. WIP

**Comment by Sreading88** [comment]
Thanks for working on this. Makes a big difference for us tradeskillers. I don't believe magic jewlery making tools are working either. Or the veldan hammer.

**Comment by hgesler** [comment]
Magic carpentry and forging tools should be fixed now. Testing fix for jeweler's mitt's / mystic jewelers tools.
