### ISSUE TITLE
Pathfinding when targeting monsters fails

### ISSUE THREAD

**Issue by AndrewCloss** [IronWillGames/AshenEmpires#30]
When clicking to attack a monster (regardless of control scheme), the PC moves one tile then pre-emptively stops.

**Comment by davidjreese** [comment]
I was unable to repro this. I tested it and whenever I am within a tile it won't move me to the target. Let me know if there is a specific scenario in which this happens if it is still happening.

**Comment by AndrewCloss** [comment]
When at a standstill, clicking X many tiles away on an enemy will move the PC only 1 step instead of X and then cancel the rest of the action.
