### ISSUE TITLE
Cannot type in a quantity when buying/selling items in shop

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/AshenEmpires#32]
Repro steps:
1. Talk to a shop NPC to open up the buy/sell window
2. Try to buy something from the 2nd, 3rd, or 4th row in the currently visible buy list, that has a quantity of more than 1, make sure the input box is focused, and try typing a number
3. The hot bar corresponding to the number you are trying to type is opened/closed instead of the number going into the input box
4. Do the same thing with the sell list, with the 3rd, or 4th row that has a quantity of more than 1 that can be sold, and try to type in a number to the focused input box. Hot bars are opened/closed instead of a number being typed

Note, it doesn't repro all of the time for some reason, but it happens to me most of the time, especially with a freshly opened shop window. Not sure what it is I'm doing in the cases it doesn't repro.

https://user-images.githubusercontent.com/72478718/188878827-6a38a0ce-cc37-4e75-a0fd-4f2f9928d954.mp4

**Comment by davidjreese** [comment]
Think I found this and fixed it. Tested with Monster Manual open and other scenarios and seems to work now.
