### ISSUE TITLE
Login Screen Image Not Scaling

### ISSUE THREAD

**Issue by GM-Odran** [IronWillGames/AshenEmpires#35]
![image](https://user-images.githubusercontent.com/112826917/188970750-effed197-0c14-4fdc-b04d-c6fb794f312d.png)

Display: 1920 x 1080
Game: 1024 x 768

**Comment by curxxx** [comment]
duplicate of https://github.com/IronWillGames/AshenEmpires/issues/1

**Comment by Plutoooooooooooo** [comment]
@IronWillGames can you please merge with #1

**Comment by davidjreese** [comment]
Might have found this. Need someone who can repo it to test in STAGE
