### ISSUE TITLE
Client freezes whenever monitor configuration changes or when resuming from screensaver

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/AshenEmpires#4]
Can be repro'd by either changing the number of external displays that are plugged in, or letting the computer go into screensaver mode and then resuming from screensaver. The game client is totally frozen visually (but sounds still go through). Can be unfrozen at the moment by just alt tabbing back and forth.

**Comment by davidjreese** [comment]
Windowed and Fullscreen windowless are supported now. Windows remember the FS and WIndows state if you toggle between them.
