### ISSUE TITLE
Plague spell can't be cast in Safe zones

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/AshenEmpires#40]

**Comment by hgesler** [comment]
This should be fixed now; it will check for dwelling first, and if that dwelling is in a safe zone it will prevent it from being cast. This will prevent majority of issues - no abuse on afk players, and players can still cast in the safe zone hunting areas around silvest/krog/whisperdale. The only exception will be settings where it is considered a dwelling. Any danger areas that are named, for example, are dwellings. Not much I can do about that. They are used for Dynamic Quests.
