### ISSUE TITLE
Game produces out-of-bounds windows by default

### ISSUE THREAD

**Issue by curxxx** [IronWillGames/AshenEmpires#41]
See: 
![](https://media.discordapp.net/attachments/695813954018213958/1017576069781540914/unknown.png)

This is despite all the troubleshooting including manually changing resolution and altering UIConfigs with ones from a known working installation (with the same resolution) 

See this conversation for specifics: https://discord.com/channels/695812967463256084/695813954018213958/1017570498114228256

**Comment by davidjreese** [comment]
I recommend deleting your AE folder in steam and doing a fresh / complete reinstall with the new version being released tonight (9.21).

I tried and tried to reproduce this but was not able to. if it stil happens, can you reopen this issue and put the resolution you are running (for windows) and any data about resolution for the game window + video card brand, etc...?
