### ISSUE TITLE
Client selects an unsupported resolution by default

### ISSUE THREAD

**Issue by curxxx** [IronWillGames/AshenEmpires#42]
In rare circumstances the game client upon first launch defaults to a resolution not supported by the player's monitor.

This can cause graphical messiness such as seen below: 

![](https://media.discordapp.net/attachments/695813954018213958/1017576787913494638/unknown.png)

**Comment by davidjreese** [comment]
Fixed and fixed the draw issue on smaller resolutions than the giant source art for splash screens
