### ISSUE TITLE
Invisible item in inventory after quest turn in

### ISSUE THREAD

**Issue by reikoshea** [IronWillGames/AshenEmpires#44]
If you gather more than 20 (22 for example) scorpion stings for the krog quest. The NPC will take the stack of stingers, but leave an "invisible" stack of 2 scorpion stings in your backpack. You wont be able to see the item unless you log out and back in again.

![image](https://user-images.githubusercontent.com/4267199/189436718-6279bcbd-1081-4145-a286-3e1b55d213b2.png)

**Comment by hgesler** [comment]
redid this so she does a findandconsume from player's backpack rather than in an onoffer function
