### ISSUE TITLE
Suggestion to add 1 free orb reset for a mid level player.

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/AshenEmpires#46]
Lots of newbies typically make a mistake in their orbs. I don't love this, as it is essentially a free orb reset now for each leveled char.

**Comment by AESeryth** [comment]
Maybe hand out No Drop runeshards at certain patron amounts or with the Parian quests

**Comment by hgesler** [comment]
Added npc to Josody that will give 1 free reset. I like idea of no drop runeshards here or there as quest rewards - good idea.
