### ISSUE TITLE
Unable to loot amphibious corpses from land

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/AshenEmpires#51]
If a creature with an amphibious walk type dies on water (snakes, river caiman, etc) and player does not have autoloot/partyloot on, they cannot open the corpse to retrieve it. A minor issue. 

Fairly certain this is related to some measures put in place to prevent players from looting a sea creature corpse.

**Comment by EJaynes** [comment]
To prevent looting sea creature as well as boat corpses/flotsams from land. This was the original method for smuggling goods to Valinor. Should change this rule to only prevent looting of sea creature and player boat corpses from land.
