### ISSUE TITLE
Client frequently disconnecting when talking to the shop NPCs

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/AshenEmpires#52]
Happens to me multiple times a day, as soon as I click on a shop NPC and it attempts to show the buy/sell window, I get that lost connection to server popup and I disconnect. Haven't been able to figure out consistent repro steps yet, will keep observing.

**Comment by davidjreese** [comment]
Doesn't seem to be happening anymore. Will create a new issue or reopen if it starts acting up
