### ISSUE TITLE
Backpack dropping on H / L is currently the same as Ascension

### ISSUE THREAD

**Issue by Plutoooooooooooo** [IronWillGames/AshenEmpires#6]
Backback dropping on H / L is currently the same as Ascension however on Legends there is no head in the backpack so nobody is able to resurrect someone elses body.

**Comment by hgesler** [comment]
Server config looks like its set up properly - all servers set to 1.0 except ascension which is variable per align, as designed.

What are their alignments?

**Comment by GM-Odran** [comment]
> Server config looks like its set up properly - all servers set to 1.0 except ascension which is variable per align, as designed.
> 
> What are their alignments?

Different for all aligns, have not seen one backpack drop for crusader, worse alignments are dropping backpack like 1 in 5 deaths.

**Comment by hgesler** [comment]
then it sounds like they are using the pvp02 flavor ruleset.

**Comment by davidjreese** [comment]
Found the issue - the BackpackDropChance function was cut/paste from the equip one. But, none of the chances were updated for backpack chances, was still using equip chances.
