### ISSUE TITLE
Pumpkin Pie stam issue

### ISSUE THREAD

**Issue by Hail-Yea-Brother** [IronWillGames/AshenEmpires#62]
The +1 stam from Pumpkin Pie only lasts 15 minutes compared to Pumpkin Bread and Pumpkin Snacks +1 stam lasting 30 minutes

**Comment by marmotini** [comment]
I think all pies have a short stam regen duration compared to the stat boost duration 😭  would be nice for the stam regen duration to be 30 min

**Comment by hgesler** [comment]
I show the stam regen effect from pumpkin pie lasting 30 min.
