### ISSUE TITLE
Bulwark Might different cooldown

### ISSUE THREAD

**Issue by GM-Odran** [IronWillGames/AshenEmpires#64]
Bulwark Might is the only buff with a different cooldown timer

**Comment by hgesler** [comment]
@GM-Odran different than what other spell? Or what is the expected length of time? It appears to last 2 hours, 4 with the robe of dark rites; this is the same as Fortify, Holy Aura, Cerebral Thought, Resplendence, Alacrity, Grandeur, Speed of the Gazelle, and Blessing of Malax.

**Comment by GM-Odran** [comment]
@hgesler Bulwark Might lasts longer than all other buff spells (including the ones you mentioned above). Have tested it myself and it's been brought up many times in Discord. It appears to last like an extra 10 mins?

**Comment by hgesler** [comment]
Ah I see. Ok, I have removed that random extra time added at factor of body skill level.
