### ISSUE TITLE
Add warning to account linking popup and confirmation page about possibility to lose characters

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/AshenEmpires#67]
On both the in-game popup and also the linking confirmation web page (shown below in screenshots), there should be a warning message telling people that any characters they created on their Steam account will not be accessible anymore after they link to their old Pixel Mine account; only the old characters will be accessible. Maybe something like: `WARNING: Any new characters you created will NOT be carried over! Only the characters from your Pixel Mine account will appear after linking.`

![image](https://user-images.githubusercontent.com/72478718/190916041-022f5840-3430-4f93-8429-7a6e414d5ce8.png)

![image](https://user-images.githubusercontent.com/72478718/190916045-e926c34c-8468-4bac-8fc3-dc655a33b211.png)

**Comment by davidjreese** [comment]
Added warnings to website and AE + Dransik dialogs about losing progress on CURRENT/THIS account.
