### ISSUE TITLE
Follower Marker box being left in player backpack in some situations

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/AshenEmpires#8]
Still gathering info on how its getting into this state. Should be cleaned up on login.

**Comment by EJaynes** [comment]
These containers allow players to add items to them, rather than just remove (should be solely for reclaiming their leftover/des-pawned pet inventory), and apparently reduces weight of contents by 100%.

**Comment by hgesler** [comment]
Need to figure out how the cleanup script is not working when player logs in without a follower.

The follower marker is created when player logs out; all items from follower put in there, then when the player logs in the marker is used to recreate the follower and put its inventory back inside of it. Presumably something is happening on login that causes the script not destroy the marker.

**Comment by hgesler** [comment]
@davidjreese  I'm trying to figure out why this follower marker box is not working on the login sequence. I haven't changed anything in this part of script in some time but it seems that sometimes players are not getting their followers back when they login. The workflow is this:

1. Player tames a follower in game with a whip/training tool or charisma of ulthien spell (not a totem-summoned pet)
2. Player logs out. Follower marker created onlogout, box put in player's bp that has the type health and inventory of the follower)
3. Player logs in and CreateFollowers is called. Looks for marker box and creates follower based on that, then destroys the box. This is in playergeneric.use in the "CreateFollowers" function.

**Comment by davidjreese** [comment]
looking at this. i am not really familiar with this code. 

when the marker box fails to destroy, does it still create all the followers? or does that fail fully or partially when this happens?

**Comment by davidjreese** [comment]
Remedy steps:
1. add additional usecode - remove ALL markers after the first one is processed (cleans up in case more than 1 exists b/c of this bug)
2. in progress: seems to have required a FULL RELOG but I got follower marker 23 to stay with me and can see it in my backpack now.

**Comment by davidjreese** [comment]
Found and fixed and added cleanup.
